FROM nginx:alpine 

COPY ./nginx.conf.template /etc/nginx/nginx.conf.template
# COPY ./nginx.conf /etc/nginx/nginx.conf
# RUN envsubst '$API_CONTAINER_NAME,$API_PORT,$APP_CONTAINER_NAME,$APP_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
