FROM node:lts-alpine as base

WORKDIR /var/www/app

COPY package*.json ./
COPY .npmrc .npmrc

RUN npm ci
# Opt-out of Next.js telemetry
RUN npm run next-telemetry:disable

COPY . .


FROM base as production

ENV NODE_PATH=./dist
RUN npm run build